FROM node:20-alpine

WORKDIR /usr/src/app

# Instalar bash
RUN apk add --no-cache bash

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar solo el schema de Prisma y generar cliente
COPY prisma ./prisma
RUN npx prisma generate

# Copiar el resto del proyecto
COPY . .

# Exponer puerto
EXPOSE 3000

# Comando por defecto
CMD ["npm", "run", "start:dev"]
